### ISSUE TITLE
[DOCKERIZED] Avoid link environment variables 

### ISSUE THREAD

**Issue by frascuchon** [vfrico/kge-server#2]
Communication between containers with link environment variables is deprecated. See [this](https://docs.docker.com/compose/link-env-deprecated/). In docker-compose v2 , this behaviour is discarded

Maybe, better approach is define container environments variables to define in runtime

**Comment by vfrico** [comment]
I've just uploaded inside `images/` folder a docker-compose.yml and some other files. For a _really_ basic usage it may work, but I'm afraid of it can break anytime.

Also, environment variables are no longer being used.

Would be nice to get some feedback
