### ISSUE TITLE
Wrong endpoint - creating new and empty dataset

### ISSUE THREAD

**Issue by leonardomra** [vfrico/kge-server#3]
hi vfrico,
on the documentation it's written that the endpoint to create a new dataset is 
`POST /dataset?type=(int: dataset_type)`
however, it should be
`POST /datasets?dataset_type=(int: dataset_type)`
best!
Leonardo

**Comment by vfrico** [comment]
You are completely right. I'm upgrading the docs with that fixed.
Thanks!
