### ISSUE TITLE
Table algorithm from server.db is empty

### ISSUE THREAD

**Issue by leonardomra** [vfrico/kge-server#4]
Hi vfrico,
The table algorithm from server.db is empty. Therefore, cannot train the dataset.
I saw that there is an endpoint `POST /algorithms/` to include an algorithm, but I'm not sure about the parameters I should pass. Is it possible list them here and recommend possible values?
best,
Leonardo

**Comment by vfrico** [comment]
I've uploaded the new docs. It has a sample HTTP request to POST a new algorithm. https://vfrico.github.io/kge-server/modules/restservice.html#post--algorithms-
